# Generated by Django 5.0.2 on 2024-02-07 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_kick_kickvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickvote',
            name='kick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kickvote_kick', to='users.kick'),
        ),
    ]
