# Generated by Django 5.0.2 on 2024-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_kickvote_kick'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pics'),
        ),
    ]
