# Generated by Django 5.0.2 on 2024-02-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_kick_group_kick_vote_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kickvote',
            name='kick',
        ),
        migrations.RemoveField(
            model_name='kickvote',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Kick',
        ),
        migrations.DeleteModel(
            name='KickVote',
        ),
    ]
